
CREATE TABLE `error_log_monitor` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CREATED_TS` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EMAIL_SENT` TINYINT(1) DEFAULT NULL,
  `ERRTXT` VARCHAR(255) DEFAULT 'NULL',
  `STACK_TRACE` BLOB,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=331 DEFAULT CHARSET=utf8


DELIMITER $$

CREATE TRIGGER MONITOR_ERROR_LOG 
AFTER INSERT ON ERROR_LOG FOR EACH ROW 
BEGIN 
DECLARE errorText VARCHAR(255); 
DECLARE stackTrace BLOB; 
SELECT ERRTXT FROM ERROR_LOG ORDER BY ID DESC LIMIT 1 INTO errorText; 
SELECT STACK_TRACE FROM ERROR_LOG ORDER BY ID DESC LIMIT 1 INTO stackTrace; 
INSERT INTO ERROR_LOG_MONITOR (EMAIL_SENT, ERRTXT, STACK_TRACE) VALUES(0, errorText, stackTrace);
END$$

DELIMITER ;

SELECT * FROM ERROR_LOG_MONITOR